"""Structured action planning models."""

from __future__ import annotations

from typing import Any, Dict, List, Literal

from pydantic import BaseModel, Field, model_validator

from src.planner.action_registry import ACTION_SPECS, normalize_action_payload

ActionType = Literal[
    "run_command",
    "open_application",
    "open_url",
    "list_directory",
    "read_file",
    "write_file",
    "take_screenshot",
    "focus_window",
    "type_text",
    "press_key",
    "mouse_click",
    "find_files",
    "search_text",
    "read_multiple_files",
    "get_system_info",
    "request_confirmation",
    "respond_only",
]

RiskLevel = Literal["low", "medium", "high", "critical"]


class PlannedAction(BaseModel):
    """One structured action emitted by the planner."""

    action_type: ActionType
    args: Dict[str, Any] = Field(default_factory=dict)
    reason: str = Field(min_length=1)
    risk_level: RiskLevel = "low"
    requires_confirmation: bool = False

    @model_validator(mode="before")
    @classmethod
    def normalize_raw_action(cls, data: object) -> object:
        if isinstance(data, dict):
            normalized, _ = normalize_action_payload(data)
            return normalized
        return data

    @model_validator(mode="after")
    def validate_required_args(self) -> "PlannedAction":
        spec = ACTION_SPECS.get(self.action_type)
        keys = list(spec.required_args) if spec else []
        missing = [key for key in keys if key not in self.args]
        if missing:
            raise ValueError(f"Missing args for {self.action_type}: {', '.join(missing)}")
        return self


class ActionPlan(BaseModel):
    """Top-level action plan generated by the planner."""

    task_id: str = Field(min_length=1)
    goal: str = Field(min_length=1)
    actions: List[PlannedAction] = Field(min_length=1)
    final_response_style: Literal["concise", "detailed"] = "concise"
    planner_notes: str = ""
