"""Structured action planning models."""

from __future__ import annotations

from typing import Any, Dict, List, Literal

from pydantic import BaseModel, Field, model_validator

ActionType = Literal[
    "run_command",
    "open_application",
    "open_url",
    "list_directory",
    "read_file",
    "write_file",
    "take_screenshot",
    "focus_window",
    "type_text",
    "press_key",
    "mouse_click",
    "request_confirmation",
    "respond_only",
]

RiskLevel = Literal["low", "medium", "high", "critical"]


class PlannedAction(BaseModel):
    """One structured action emitted by the planner."""

    action_type: ActionType
    args: Dict[str, Any] = Field(default_factory=dict)
    reason: str = Field(min_length=1)
    risk_level: RiskLevel = "low"
    requires_confirmation: bool = False

    @model_validator(mode="after")
    def validate_required_args(self) -> "PlannedAction":
        required_keys: Dict[str, List[str]] = {
            "run_command": ["command"],
            "open_application": ["name"],
            "open_url": ["url"],
            "list_directory": ["path"],
            "read_file": ["path"],
            "write_file": ["path", "content"],
            "focus_window": ["title"],
            "type_text": ["text"],
            "press_key": ["key"],
            "mouse_click": ["x", "y"],
            "request_confirmation": ["prompt"],
            "respond_only": ["message"],
        }
        keys = required_keys.get(self.action_type, [])
        missing = [key for key in keys if key not in self.args]
        if missing:
            raise ValueError(f"Missing args for {self.action_type}: {', '.join(missing)}")
        return self


class ActionPlan(BaseModel):
    """Top-level action plan generated by the planner."""

    task_id: str = Field(min_length=1)
    goal: str = Field(min_length=1)
    actions: List[PlannedAction] = Field(min_length=1)
    final_response_style: Literal["concise", "detailed"] = "concise"
    planner_notes: str = ""

